### ISSUE TITLE
No way to rotate fonts?

### ISSUE THREAD

**Issue by tarasius** [rm-hull/max7219#10]
Good day.
Is there any way to rotate font without re-specifying constants of characters? I.e. some rotation parameter. If no, it would be nice to have.
P.S.: I have Cyrillic font if somebody needs it.

**Comment by rm-hull** [comment]
Hello, it should be quite easy to extend the code do some bit-fiddling to rotate 90, 180 or 270 degrees. I'll have a look at implementing it in the next few days.

In the meantime, if you're Cyrillic font works, then by all means fork the project, add to the `font.py` file and submit a pull request

**Comment by rm-hull** [comment]
From Graphics Gems II

Yap, Sue-Ken, **A Fast 90-Degree Bitmap Rotator**, p. 84-85, code: p. 514-515, http://tog.acm.org/resources/GraphicsGems/gemsii/rotate8x8.c.

Just need to port it across to Python

**Comment by rm-hull** [comment]
Ah! I see now why you want to be able to rotate (I just merged your PR) ... so I will write a little python script to rotate the UKR_FONT definitions,
