### ISSUE TITLE
rotate8x8

### ISSUE THREAD

**Issue by trogper** [rm-hull/max7219#18]
there's an error in rotate8x8.py when combined with scrolling
simplest repro of this would be taking "Scrolling and pixel setting..." from matrix_test.py and setting device.orientation(180) before running it
source: http://pastebin.com/jzWvuYK7

  File "/usr/local/lib/python2.7/dist-packages/max7219/led.py", line 361, in _rotate
    tile = rotate(tile)
  File "/usr/local/lib/python2.7/dist-packages/max7219/rotate8x8.py", line 37, in rotate
    assert 0 <= value < 256, 'Value {0} outside range 0..255'.format(value)
AssertionError: Value 496 outside range 0..255

**Comment by rm-hull** [comment]
ah right - looks like `scroll_down` just does `<<1` .. it should probably `& 0xff` as well. 

Will look at getting this fixed shortly.

Thanks for reporting!
