### ISSUE TITLE
Scrolling speed

### ISSUE THREAD

**Issue by marksev1** [rm-hull/max7219#21]
Is it possible to modify the scrolling speed of the text displayed on these lcds?

**Comment by rm-hull** [comment]
If you are using the `show_message` method (see https://github.com/rm-hull/max7219/blob/master/max7219/led.py#L317) then you can alter the text scrolling speed by setting the `delay` named parameter as follows:

```python
device.show_message("Slow scroll", delay=0.5)

device.show_message("Fast scroll", delay=0.01)
```

If that parameter is omitted, then the scroll delay is 0.05 seconds

**Comment by marksev1** [comment]
Pretty cool, so I just add the delay parameter. Thanks for the tip! I thought it was there but needed an confirmation.
