### ISSUE TITLE
Showing text without scrolling

### ISSUE THREAD

**Issue by bauerj** [rm-hull/max7219#29]
Is there currently a way to show some string centered (without scrolling) if it fits on the displays? It might be useful for showing things like the current time or temperature where you don't want the text to scroll.

If not, I could send you a Pull Request if you like.

**Comment by rm-hull** [comment]
Which type of display are you talking about? The 8x8 matrixes or the 7-segment displays?

If you mean the 7-segment displays, then you could use the `letter` function to position specific letters at different digit places (and it would be quite easy to wrap that up into a `write_text` function that manages left/right/centre justification). From memory, I think the position is counted from the right most digit.

The matrix version would be a tiny bit more complicated as you would need to take account of the font widths.

I'm away for a few days, so by all means go for a PR (try and stick to the PEP8 style guide and please add a docstring to any public methods).

**Comment by bauerj** [comment]
> Which type of display are you talking about? The 8x8 matrixes or the 7-segment displays?

Yes, I am talking about the 8x8 matrices. I'll send you a PR implementing it :+1:
