### ISSUE TITLE
Document supported Python versions

### ISSUE THREAD

**Issue by thijstriemstra** [rm-hull/max7219#33]
Because I'd like to know if Python 3.x is supported?

**Comment by rm-hull** [comment]
Sorry it took so long to answer this issue.
 
Python 3 _is_ supported, either by cloning the the repo & `python3 setup.py install` or `pip3 install max7219`

README.md updated

**Comment by thijstriemstra** [comment]
Thanks @rm-hull. You can also document these supported python versions using classifiers in setup.py so PyPi also knows what versions are supported.
