### ISSUE TITLE
Convert README.md to .rst

### ISSUE THREAD

**Issue by thijstriemstra** [rm-hull/max7219#35]
If README.md is converted to .rst it can be included in the readthedocs index page and serve as it's main page.

**Comment by thijstriemstra** [comment]
Let me know if you'd accept a PR.

**Comment by rm-hull** [comment]
Yes please :)

 - the docs need are in need of regeneration anyway.

- will this also fill in the pypi page which is currently empty? I had originally added _setup.cfg_ but that had little effect.

**Comment by thijstriemstra** [comment]
@rm-hull no, you need to use the `long_description` attribute to make it show up on Pypi. I'll include it in the PR.
