### ISSUE TITLE
installing error 

### ISSUE THREAD

**Issue by thib3113** [rm-hull/max7219#4]
i launch 
'''shell
sudo python setup.py install
'''
and i have this error :
'''Shell
building 'max7219.spi' extension
creating build/temp.linux-armv6l-2.7
creating build/temp.linux-armv6l-2.7/src
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c src/spi.c -o build/temp.linux-armv6l-2.7/src/spi.o
src/spi.c:20:20: fatal error: Python.h: Aucun fichier ou dossier de ce type
compilation terminated.
error: command 'gcc' failed with exit status 1
'''

**Comment by thib3113** [comment]
it's ok, just i have python by default but not python-dev

**Comment by rm-hull** [comment]
Glad you found the problem -- I'll add a section to the readme file to indicate that `python-dev` is a pre-requisite
