### ISSUE TITLE
launch with php

### ISSUE THREAD

**Issue by thib3113** [rm-hull/max7219#5]
Hello, i will launch the script by php, with an user "eva" create by me, but when i launch the script, i have : 
'''shell
can't open device: Permission denied
'''
when i make : segment = SevenSegment()

Do you have any idea ? or do you know who file i do change the rights ?

**Comment by rm-hull** [comment]
Access to SPI must be via root (or by using sudo), or if you follow the instructions here: http://quick2wire.com/non-root-access-to-spi-on-the-pi/, you can create a group called `spi` and add your user to that group

**Comment by thib3113** [comment]
thank you, i found on rasbian the group "SPI", i add it to my user and it's work :)
